### ISSUE TITLE
Setting timeout

### ISSUE THREAD

**Issue by oculos** [aaa4j/aaa4j-radius#15]
Hi,

I wonder, how can I set a value for xx seconds timeout for a client/request?

**Comment by tsyd** [comment]
You can set a timeout on all the requests by setting the `RetransmissionStrategy` when building the `RadiusClient` client:

```java
RadiusClient radiusClient = UdpRadiusClient.newBuilder()
        .secret("sharedsecret".getBytes(UTF_8))
        .address(new InetSocketAddress("127.0.0.1", 1812))
        .retransmissionStrategy(new IntervalRetransmissionStrategy(1, Duration.ofSeconds(5)))
        .build();
```

**Comment by oculos** [comment]
> You can set a timeout on all the requests by setting the `RetransmissionStrategy` when building the `RadiusClient` client:
> 
> ```java
> RadiusClient radiusClient = UdpRadiusClient.newBuilder()
>         .secret("sharedsecret".getBytes(UTF_8))
>         .address(new InetSocketAddress("127.0.0.1", 1812))
>         .retransmissionStrategy(new IntervalRetransmissionStrategy(1, Duration.ofSeconds(5)))
>         .build();
> ```

Amazing! Thank you so much for this!
