### ISSUE TITLE
Why your official website is down?

### ISSUE THREAD

**Issue by kopitetorres** [aaa4j/aaa4j-radius#6]
https://aaa4j.org cannot be opened

**Comment by tsyd** [comment]
The website hasn't been developed yet. Are you looking for documentation? The examples in [README.md](https://github.com/aaa4j/aaa4j-radius/blob/master/README.md) are a good place to start. The standard RADIUS data types and attributes are already implemented. Let me know if I can help with anything.

**Comment by kopitetorres** [comment]
I see,&nbsp;I just came into contact with the project about Radius recently.
I was thinking, if this org exists, it would be so cool ~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aaa4j/aaa4j-radius"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月27日(星期一) 凌晨3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aaa4j/aaa4j-radius] Why your official website is down? (#6)





 
The website hasn't been developed yet. Are you looking for documentation? The examples in README.md are a good place to start. The standard RADIUS data types and attributes are already implemented. Let me know if I can help with anything.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tsyd** [comment]
The website is now up: https://aaa4j.org/
